name: Update Filtered Playlist

on:
  schedule:
    - cron: "0 */3 * * *"  # Tiap 3 jam
  workflow_dispatch:       # Bisa jalan manual juga

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl grep sed

      - name: Download & filter playlists
        run: |
          mkdir -p tmp
          # Ambil sumber 1
          curl -s "https://raw.githubusercontent.com/tyo878787/my-iptv-playlist/refs/heads/tyo878787/RfK01.m3u" -o tmp/1.m3u
          # Ambil sumber 2
          curl -s "https://raw.githubusercontent.com/iptv-org/iptv/master/index.m3u" -o tmp/2.m3u

          # Gabung & filter hanya channel aktif (HTTP status 200)
          grep -E '^#EXTINF' tmp/1.m3u > merged.m3u
          grep -v '^#EXTINF' tmp/1.m3u | while read -r url; do
            if curl -s --head "$url" | grep "200" > /dev/null; then
              echo "$url" >> merged.m3u
            fi
          done

          grep -E '^#EXTINF' tmp/2.m3u >> merged.m3u
          grep -v '^#EXTINF' tmp/2.m3u | while read -r url; do
            if curl -s --head "$url" | grep "200" > /dev/null; then
              echo "$url" >> merged.m3u
            fi
          done

      - name: Commit & push changes
        run: |
          mv merged.m3u filtered_playlist.m3u
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add filtered_playlist.m3u
          git commit -m "Update filtered playlist"
          git push
