import requests
import sys
import os
from datetime import datetime, timedelta

# Konfigurasi
SOURCE_PRIVATE = "https://raw.githubusercontent.com/tyo878787/my-iptv-playlist/refs/heads/tyo878787/RfK01.m3u"
SOURCE_PUBLIC = "https://iptv-org.github.io/iptv/index.m3u"
OUTPUT_FILE = "RfK01.m3u"
REFRESH_HOURS = 6  # Interval update dalam jam
SHORT_URL = "https://rebrand.ly/RFK02"  # Menggunakan shortlink Bree Anda

def fetch_playlist(url):
    try:
        print(f"📡 Fetching playlist: {url}")
        response = requests.get(url, timeout=15)
        response.raise_for_status()
        return response.text
    except Exception as e:
        print(f"❌ Error fetching {url}: {str(e)}")
        return ""

def clean_playlist(content):
    """Bersihkan header ganda dan whitespace berlebihan"""
    cleaned = content.strip()
    if cleaned.startswith("#EXTM3U"):
        cleaned = cleaned.replace("#EXTM3U", "", 1).strip()
    return cleaned

def main():
    print("\n" + "="*50)
    print("🚀 Starting Bree IPTV Playlist Update")
    print("="*50)
    
    # Ambil playlist
    private_playlist = fetch_playlist(SOURCE_PRIVATE)
    public_playlist = fetch_playlist(SOURCE_PUBLIC)
    
    # Bersihkan dan gabungkan
    combined = ""
    if private_playlist:
        combined += clean_playlist(private_playlist) + "\n\n"
    if public_playlist:
        combined += clean_playlist(public_playlist) + "\n\n"
    
    if not combined:
        print("\n❌ Critical Error: All sources failed!")
        sys.exit(1)
    
    # Header untuk auto-update
    now_utc = datetime.utcnow()
    next_update = now_utc + timedelta(hours=REFRESH_HOURS)
    
    header = f"""#EXTM3U
## AUTO-GENERATED BY BREE IPTV SYSTEM
## Created: {now_utc.strftime("%Y-%m-%d %H:%M:%S UTC")}
## Next Update: {next_update.strftime("%Y-%m-%d %H:%M:%S UTC")}
## User Access: {SHORT_URL}
## Private Source: {SOURCE_PRIVATE}
## Public Source: {SOURCE_PUBLIC}
#REFRESH-INTERVAL:{REFRESH_HOURS * 3600}
#REFRESH-URI:{SHORT_URL}
#REFRESH-DATE:{next_update.strftime("%Y-%m-%dT%H:%M:%SZ")}
#GENERATED-BY:https://github.com/tyo878787/my-iptv-playlist\n\n"""
    
    # Gabungkan header dengan konten
    full_playlist = header + combined.strip()
    
    # Simpan ke file
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(full_playlist)
    
    print("\n" + "="*50)
    print(f"✅ Success! Playlist saved to {OUTPUT_FILE}")
    print(f"🔗 User Access URL: {SHORT_URL}")
    print(f"⏱ Next auto-refresh: {next_update.strftime('%Y-%m-%d %H:%M UTC')}")
    print("="*50)
    
    # Verifikasi file
    file_size = os.path.getsize(OUTPUT_FILE)
    print(f"📁 File size: {file_size/1024:.2f} KB")
    print(f"🔢 Channels: {full_playlist.count('#EXTINF')}")

if __name__ == "__main__":
    main()
