name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 3 * * *'  # setiap hari jam 03:00 UTC
  workflow_dispatch:      # bisa dijalankan manual

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update playlist
        run: |
          python update_playlist_async.py
