name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 */6 * * *'  # Setiap 6 jam
  workflow_dispatch:       # Bisa manual dari GitHub UI

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_playlist.py
