name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 * * * *'  # setiap 1 jam sekali
  workflow_dispatch:      # bisa juga dijalankan manual lewat GitHub UI

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Update_playlist.py
        run: python Update_playlist.py
        working-directory: scripts

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Finalplay.m3u
          if git diff --cached --quiet; then
            echo "No changes detected, skip commit"
          else
            git commit -m "Update playlist otomatis via GitHub Actions"
            git push
          fi
        continue-on-error: true
