name: Update Playlist RfK01.m3u

on:
  schedule:
    - cron: "0 */6 * * *"  # tiap 6 jam
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Run playlist update script
        run: python scripts/update_playlist.py

      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add RfK01.m3u
          git commit -m "Auto update RfK01.m3u playlist"
          git push
        continue-on-error: true  # supaya workflow sukses walaupun gak ada perubahan
