name: Update Playlist & Deploy to Pages

on:
  schedule:
    - cron: "0 */3 * * *"  # Tiap 3 jam
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download playlists
        run: |
          curl -s "https://raw.githubusercontent.com/tyo878787/my-iptv-playlist/tyo878787/playlist1.m3u" -o playlist1.m3u
          curl -s "https://raw.githubusercontent.com/iptv-org/iptv/master/index.m3u" -o playlist2.m3u

      - name: Gabung playlist jadi Finalplay.m3u
        run: |
          echo "#EXTM3U" > Finalplay.m3u
          grep -v '^#EXTM3U' playlist1.m3u >> Finalplay.m3u
          grep -v '^#EXTM3U' playlist2.m3u >> Finalplay.m3u

      - name: Deploy ke branch gh-pages
        run: |
          mkdir public
          cp Finalplay.m3u public/
          echo "www.rafkichanel.my.id" > public/CNAME
          
          cd public
          git init
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy playlist to GitHub Pages"
          git branch -M gh-pages
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force origin gh-pages
