name: Update IPTV Playlist

on:
  workflow_dispatch:        # bisa manual run
  schedule:
    - cron: "0 */3 * * *"   # otomatis tiap 3 jam sekali

permissions:
  contents: write           # penting supaya bisa commit & push

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Jalankan Update_playlist.py (auto commit & push)
        run: python Update_playlist.py
        working-directory: scripts
