name: Update Playlist Sederhana

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          
      - name: Install requests
        run: pip install requests
        
      - name: Run script
        run: python update_playlist.py
        
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add RfK01.m3u
          git diff --cached --quiet || git commit -m "Update playlist: $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
