name: Update IPTV Playlist

on:
  schedule:
    - cron: "0 */6 * * *"  # Setiap 6 jam
  workflow_dispatch:        # Memungkinkan trigger manual

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Download Playlist
        run: |
          # Unduh playlist menggunakan curl, dengan timeout 30 detik
          curl -L --max-time 30 -o playlist.m3u "https://rebrand.ly/2b660d"
          
          # Buat file log update
          echo "Last Update: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > LAST_UPDATE.txt
          echo "Source: https://privatebin.net/?743289ef7dd5d999#8EmJpx4uVkxGgRSBatQuKt2Vay2eYyNyGfEJJe4URBxR" >> LAST_UPDATE.txt
          
          # Jika file playlist kosong, buat playlist dengan pesan error
          if [ ! -s playlist.m3u ]; then
            echo "#EXTM3U" > playlist.m3u
            echo "# ERROR: Failed to download playlist" >> playlist.m3u
          fi

      - name: Commit Changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add playlist.m3u LAST_UPDATE.txt
          
          # Commit hanya jika ada perubahan
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update playlist [skip ci]"
            git push "https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          fi
