- name: Filter active channels and create Finalplay.m3u
  run: |
    echo "#EXTM3U" > Finalplay.m3u

    filter_playlist() {
      local file=$1
      local total=$(grep -c '^#EXTINF' "$file")
      local count=0

      echo "Mulai filter playlist dari $file dengan total channel: $total"

      # Baca baris #EXTINF dan url berikutnya, skip baris kosong
      while read -r line1 && read -r line2; do
        if [[ -z "$line1" || -z "$line2" ]]; then
          continue
        fi
        echo "Cek channel: $line2"
        if curl -s --head --fail "$line2" | head -n 1 | grep -q "200"; then
          echo "Aktif: $line2"
          echo "$line1" >> Finalplay.m3u
          echo "$line2" >> Finalplay.m3u
          count=$((count + 1))
        else
          echo "Mati: $line2"
        fi
      done < <(grep -A1 '^#EXTINF' "$file" | sed '/^--$/d')

      echo "Selesai filter $count channel aktif dari $total di $file"
    }

    filter_playlist tmp/1.m3u
    filter_playlist tmp/2.m3u
