name: Generate Xtream API

on:
  schedule:
    - cron: '0 */3 * * *'   # jalan tiap 3 jam
  workflow_dispatch:        # bisa run manual lewat UI

permissions:
  contents: write

jobs:
  generate-xtream:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install requests

      # 4️⃣ Jalankan generate_xtream.py dari root repo
      - name: Generate Xtream API
        run: python generate_xtream.py

      # 5️⃣ Commit & push hanya jika ada perubahan
      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto update Xtream API"
          git push
