name: Update Playlist ke GitHub Pages

on:
  schedule:
    - cron: "0 */3 * * *" # Tiap 3 jam
  workflow_dispatch: # Bisa jalan manual juga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download playlists
        run: |
          curl -s "https://raw.githubusercontent.com/tyo878787/my-iptv-playlist/tyo878787/playlist1.m3u" -o playlist1.m3u
          curl -s "https://raw.githubusercontent.com/iptv-org/iptv/master/index.m3u" -o playlist2.m3u

      - name: Gabung playlist jadi index.m3u
        run: |
          echo "#EXTM3U" > index.m3u
          grep -v '^#EXTM3U' playlist1.m3u >> index.m3u
          grep -v '^#EXTM3U' playlist2.m3u >> index.m3u

      - name: Deploy ke gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard

          mv index.m3u index.m3u
          echo "www.rafkichanel.my.id" > CNAME

          git add index.m3u CNAME
          git commit -m "Update playlist otomatis"
          git push origin gh-pages --force
