- name: Update playlist
  run: python update_playlist.py
  
- name: Debug Info
  run: |
    echo "===== DEBUG INFO ====="
    ls -lh
    head -n 20 RfK01.m3u || true
    echo "======================"
    
- name: Upload Playlist Artifact
  uses: actions/upload-artifact@v3
  if: always()
  with:
    name: playlist-debug
    path: |
      RfK01.m3u
      update_playlist.log  # Jika script Anda membuat log file
