name: Update Filtered Playlist

on:
  schedule:
    - cron: "0 */3 * * *"  # Tiap 3 jam
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl grep sed

      - name: Download playlists
        run: |
          mkdir -p tmp
          curl -s "https://raw.githubusercontent.com/tyo878787/my-iptv-playlist/refs/heads/tyo878787/playlist1.m3u" -o tmp/1.m3u
          curl -s "https://raw.githubusercontent.com/iptv-org/iptv/master/index.m3u" -o tmp/2.m3u

      - name: Filter active channels and create Finalplay.m3u
        run: |
          echo "#EXTM3U" > Finalplay.m3u

          # Fungsi untuk filter playlist
          filter_playlist() {
            local file=$1
            local total=$(grep -c '^#EXTINF' "$file")
            local count=0

            # Baca baris #EXTINF dan url berikutnya
            while read -r line1 && read -r line2; do
              if curl -s --head --fail "$line2" | head -n 1 | grep -q "200"; then
                echo "$line1" >> Finalplay.m3u
                echo "$line2" >> Finalplay.m3u
                count=$((count + 1))
              fi
            done < <(grep -A1 '^#EXTINF' "$file" | sed '/^--$/d')

            echo "Filtered $count of $total channels from $file"
          }

          filter_playlist tmp/1.m3u
          filter_playlist tmp/2.m3u

      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Finalplay.m3u
          git commit -m "Update filtered playlist"
          git push
