name: Update Playlist

on:
  schedule:
    - cron: "0 */6 * * *" # update tiap 6 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Jalankan update playlist
        run: python scripts/update_playlist.py

      - name: Commit hasilnya
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Auto update playlist" || echo "Tidak ada perubahan"
          git push
