name: Bree IPTV Auto-Update

on:
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours at minute 0
  workflow_dispatch:  # Manual trigger option

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run Bree update script
        run: python update_playlist.py

      - name: Commit and Push Changes
        run: |
          git config user.name "bree-iptv-bot"
          git config user.email "bree@example.com"
          git add RfK01.m3u
          
          # Hanya commit jika ada perubahan
          if [ -z "$(git status --porcelain RfK01.m3u)" ]; then
            echo "🟢 No changes in playlist"
          else
            git commit -m "Bree Auto-Update: $(date -u +'%Y-%m-%d %H:%M UTC')"
            git push
            echo "🚀 Playlist updated and pushed"
          fi
