name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 */3 * * *'   # setiap 3 jam sekali
  workflow_dispatch:        # bisa dijalankan manual lewat GitHub UI

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Jalankan Update_playlist.py
        run: python Update_playlist.py
        working-directory: scripts

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add scripts/Finalplay04.m3u || true
          if git diff --cached --quiet; then
            echo "✅ Tidak ada perubahan, skip commit"
          else
            git commit -m "Update Finalplay04.m3u otomatis via GitHub Actions"
            git push
          fi
