name: Auto Update IPTV Playlist

on:
  schedule:
    - cron: "0 */3 * * *"  # otomatis tiap 3 jam
  workflow_dispatch:

jobs:
  update_playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run update script
        run: |
          python3 scripts/update.py || python3 scripts/your_script.py

      - name: Commit & push update
        run: |
          git config --global user.name "rafkichanel"
          git config --global user.email "EMAIL_KAMU"
          git add Finalplay.m3u LAST_UPDATE.txt
          git commit -m "Auto-update playlist"
          git push
