name: Auto Update IPTV Playlist

on:
  schedule:
    - cron: "0 */3 * * *"   # jalan tiap 3 jam
  workflow_dispatch:

jobs:
  update_playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Jalankan script update
        run: |
          python3 scripts/update.py

      - name: Commit & push perubahan
        run: |
          git config --global user.name "rafkichanel"
          git config --global user.email "andiprasetyooo923@gmail.com"
          git add Finalplay.m3u LAST_UPDATE.txt
          git commit -m "Auto-update playlist dengan timestamp"
          git push
